# Generated by Django 2.1.7 on 2019-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_posttagrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTagRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_post', models.IntegerField()),
                ('id_tag', models.IntegerField()),
            ],
        ),
    ]
