# Generated by Django 2.1.7 on 2019-07-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190702_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttagrelation',
            name='id_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='posttagrelation',
            name='id_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Tag'),
        ),
    ]
