# Generated by Django 2.1.7 on 2019-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190702_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttagrelation',
            name='id_post',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='posttagrelation',
            name='id_tag',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
